ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_location text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_house_number text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_street text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_barangay text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_city text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_province text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_postal_code text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_country text;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_lat double precision;
ALTER TABLE supplier_reports ADD COLUMN IF NOT EXISTS supplier_lng double precision;
